# Generated by Django 6.0.1 on 2026-01-13 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gecko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('morph', models.CharField(blank=True, max_length=100, verbose_name='모프')),
                ('gender', models.CharField(choices=[('Male', '수컷'), ('Female', '암컷'), ('Unknown', '미구분')], default='Unknown', max_length=10, verbose_name='성별')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='해칭일(생일)')),
                ('adoption_date', models.DateField(blank=True, null=True, verbose_name='입양일')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='gecko_profiles/', verbose_name='프로필 사진')),
                ('description', models.TextField(blank=True, verbose_name='특이사항')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_children', to='geckos.gecko', verbose_name='모(엄마)')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sire_children', to='geckos.gecko', verbose_name='부(아빠)')),
            ],
        ),
        migrations.CreateModel(
            name='CareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(verbose_name='기록 날짜')),
                ('log_type', models.CharField(choices=[('Feeding', '피딩'), ('Weight', '체중측정'), ('Shedding', '탈피'), ('Cleaning', '청소'), ('Etc', '기타')], default='Feeding', max_length=20)),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='무게(g)')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('image', models.ImageField(blank=True, null=True, upload_to='care_logs/')),
                ('gecko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='geckos.gecko')),
            ],
        ),
    ]
