# Generated by Django 5.1.4 on 2026-01-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geckos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carelog',
            name='egg_condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='carelog',
            name='egg_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carelog',
            name='is_fertile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gecko',
            name='is_ovulating',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carelog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gecko',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
