# Generated by Django 5.1.4 on 2026-01-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geckos', '0002_carelog_egg_condition_carelog_egg_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carelog',
            name='log_type',
            field=models.CharField(choices=[('Feeding', '피딩'), ('Weight', '체중측정'), ('Shedding', '탈피'), ('Cleaning', '청소'), ('Etc', '기타'), ('Laying', 'Laying')], default='Feeding', max_length=20),
        ),
    ]
