# Generated by Django 5.1.4 on 2026-01-13 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geckos', '0003_alter_carelog_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carelog',
            name='mating_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carelog',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mating_logs', to='geckos.gecko'),
        ),
        migrations.AlterField(
            model_name='carelog',
            name='log_type',
            field=models.CharField(choices=[('Feeding', '피딩'), ('Weight', '체중측정'), ('Shedding', '탈피'), ('Cleaning', '청소'), ('Etc', '기타'), ('Laying', 'Laying'), ('Mating', 'Mating')], default='Feeding', max_length=20),
        ),
    ]
