# Generated by Django 5.1.4 on 2026-01-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geckos', '0004_carelog_mating_success_carelog_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carelog',
            name='partner_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
