# Generated by Django 5.1.4 on 2026-01-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geckos', '0005_carelog_partner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gecko',
            name='acquisition_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gecko',
            name='acquisition_type',
            field=models.CharField(choices=[('Purchased', '입양 (분양)'), ('Hatched', '직접 해칭 (Self-Hatched)'), ('Rescue', '구조/기타')], default='Purchased', max_length=20),
        ),
        migrations.AddField(
            model_name='gecko',
            name='has_spots',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gecko',
            name='mbd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gecko',
            name='tail_loss',
            field=models.BooleanField(default=False),
        ),
    ]
