# Generated by Django 5.1.4 on 2026-01-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geckos', '0006_gecko_acquisition_source_gecko_acquisition_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gecko',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
