# Generated by Django 5.1.4 on 2026-01-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geckos', '0007_gecko_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='gecko',
            name='dam_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gecko',
            name='sire_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
