# Generated by Django 5.1.4 on 2026-01-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geckos', '0008_gecko_dam_name_gecko_sire_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carelog',
            name='expected_morph',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
