# Generated by Django 5.1.4 on 2026-01-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geckos', '0009_carelog_expected_morph'),
    ]

    operations = [
        migrations.AddField(
            model_name='carelog',
            name='expected_hatching_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carelog',
            name='incubation_temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
