# Generated by Django 5.1.4 on 2026-03-20 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geckos', '0012_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeckoPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gecko_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gecko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='geckos.gecko')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
